"""Add date_posted to Post

Revision ID: 38ff0b867918
Revises: be1b25a7573c
Create Date: 2025-05-15 16:03:52.276807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ff0b867918'
down_revision = 'be1b25a7573c'
branch_labels = None
depends_on = None


from datetime import datetime

def upgrade():
    with op.alter_column('posts', 'date_posted', server_default=None):
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('date_posted')

    # ### end Alembic commands ###
